FROM centos
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app
COPY docker_homework/lib_catalog/ .
RUN yum install -y python3 python3-pip
RUN /usr/bin/pip3 install --upgrade pip
RUN /usr/bin/pip3 install -r requirements.txt
RUN sed -i "s/^ALLOWED_HOSTS.*$/ALLOWED_HOSTS=['*']/" lib_catalog/settings.py
EXPOSE 8080


# docker run -it -p 8080:8080 --link database:database task2
