FROM centos
WORKDIR /usr/src/app
COPY docker_homework/frontend/ .
RUN yum install npm -y
RUN npm install
RUN npm run build
RUN npx browserslist@latest --update-db
EXPOSE 3000
#CMD "/usr/bin/npm" "start"
#ENTRYPOINT /usr/bin/npm start && /bin/bash
