version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    stdin_open: true
    command: /usr/bin/npm start
    ports:
      - 80:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    command: /usr/bin/python3 manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - database
    # docker-compose run backend python3 manage.py migrate

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django


